import 'dart:io';
import 'dart:math';

String iso(DateTime d) => d.toIso8601String();

void main() {
  final now = DateTime.now();
  final today = DateTime(now.year, now.month, now.day);
  final rand = Random(42);

  final sampleImages = [
    'https://images.unsplash.com/photo-1459156212016-c812468e2115?w=400',
    'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=400',
    'https://images.unsplash.com/photo-1509587584298-0f3b3a3a1797?w=400',
    'https://images.unsplash.com/photo-1545241047-6083a3684587?w=400',
    'https://images.unsplash.com/photo-1512428813834-c702c7702b78?w=400',
    'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400',
  ];

  final buffer = StringBuffer();
  buffer.writeln('-- seed_test_data.sql generated by tool/generate_seed_sql.dart');
  buffer.writeln('BEGIN TRANSACTION;');

  // Generate 20 plants
  for (var i = 0; i < 20; i++) {
    final id = 'test_plant_$i';
    final name = 'Plant $i';
    final variety = 'Variety ${i % 7}';
    final purchaseDate = today.subtract(Duration(days: 30 + i * 3));
    final location = ['HomeCenter', 'Garden', 'Online', 'FlowerShop'][i % 4];
    final hasImage = rand.nextBool();
    final imagePath = hasImage ? sampleImages[i % sampleImages.length] : null;
    final interval = 4 + (i % 7); // 4-10
    final createdAt = purchaseDate;
    final updatedAt = today;

    buffer.writeln("INSERT OR REPLACE INTO plants (id,name,variety,purchaseDate,purchaseLocation,imagePath,wateringIntervalDays,createdAt,updatedAt) VALUES ('${id.replaceAll("'", "''")}', '${name.replaceAll("'", "''")}', '${variety.replaceAll("'", "''")}', ${purchaseDate != null ? "'${iso(purchaseDate)}'" : 'NULL'}, '${location.replaceAll("'", "''")}', ${imagePath != null ? "'${imagePath.replaceAll("'", "''")}'" : 'NULL'}, ${interval}, '${iso(createdAt)}', '${iso(updatedAt)}');");

    // Generate watering logs from purchaseDate up to today following interval, with occasional exceptions
    DateTime logDate = purchaseDate;
    var skipOnce = (i % 5 == 0);
    while (!logDate.isAfter(today)) {
      // maybe skip one occurrence
      if (skipOnce && logDate.isAfter(purchaseDate.add(Duration(days: 10)))) {
        skipOnce = false; // skip only once
        logDate = logDate.add(Duration(days: interval));
        continue;
      }

      final logId = 'log_${id}_water_${logDate.millisecondsSinceEpoch}';
      final note = (['Watered generously', 'Light mist', 'Bottom watering', 'Quick water']..shuffle(rand)).first;
      buffer.writeln("INSERT OR REPLACE INTO logs (id,plantId,type,date,note,createdAt,updatedAt) VALUES ('${logId}', '${id}', 'watering', '${iso(logDate)}', '${note.replaceAll("'", "''")}', '${iso(logDate)}', '${iso(logDate)}');");

      // occasional extra off-schedule
      if (i % 6 == 0 && rand.nextBool()) {
        final extraDate = logDate.add(Duration(days: 3));
        if (!extraDate.isAfter(today)) {
          final extraId = 'log_${id}_water_extra_${extraDate.millisecondsSinceEpoch}';
          buffer.writeln("INSERT OR REPLACE INTO logs (id,plantId,type,date,note,createdAt,updatedAt) VALUES ('${extraId}', '${id}', 'watering', '${iso(extraDate)}', 'Extra watering', '${iso(extraDate)}', '${iso(extraDate)}');");
        }
      }

      logDate = logDate.add(Duration(days: interval));
    }

    // fertilizer logs for some plants
    if (i % 3 == 0) {
      final fertDate = today.subtract(Duration(days: 14 + i));
      final fertId = 'log_${id}_fert_${fertDate.millisecondsSinceEpoch}';
      buffer.writeln("INSERT OR REPLACE INTO logs (id,plantId,type,date,note,createdAt,updatedAt) VALUES ('${fertId}', '${id}', 'fertilizer', '${iso(fertDate)}', 'Fertilized', '${iso(fertDate)}', '${iso(fertDate)}');");
    }

    // vitalizer logs for some plants
    if (i % 4 == 0) {
      final vitDate = today.subtract(Duration(days: 10 + i));
      final vitId = 'log_${id}_vit_${vitDate.millisecondsSinceEpoch}';
      buffer.writeln("INSERT OR REPLACE INTO logs (id,plantId,type,date,note,createdAt,updatedAt) VALUES ('${vitId}', '${id}', 'vitalizer', '${iso(vitDate)}', 'Applied vitalizer', '${iso(vitDate)}', '${iso(vitDate)}');");
    }
  }

  // Create some notes (linked to random plants)
  for (var n = 0; n < 8; n++) {
    final noteId = 'test_note_$n';
    final title = 'Note $n';
    final content = 'This is a test note #$n';
    final linkedPlants = <String>[];
    final k = 1 + rand.nextInt(4);
    for (var j = 0; j < k; j++) {
      linkedPlants.add('test_plant_${rand.nextInt(20)}');
    }
    final imagePaths = rand.nextBool() ? [sampleImages[rand.nextInt(sampleImages.length)]] : [];
    final createdAt = today.subtract(Duration(days: rand.nextInt(40)));
    final updatedAt = today;

    buffer.writeln("INSERT OR REPLACE INTO notes (id,title,content,imagePaths,plantIds,createdAt,updatedAt) VALUES ('${noteId}', '${title.replaceAll("'", "''")}', '${content.replaceAll("'", "''")}', '${imagePaths.join('|').replaceAll("'", "''")}', '${linkedPlants.join('|')}', '${iso(createdAt)}', '${iso(updatedAt)}');");
  }

  buffer.writeln('COMMIT;');

  final outDir = Directory('scripts');
  if (!outDir.existsSync()) outDir.createSync(recursive: true);
  final out = File('scripts/seed_test_data.sql');
  out.writeAsStringSync(buffer.toString());
  print('Generated scripts/seed_test_data.sql');
}
